### ISSUE TITLE
Not working URL error

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [thaleslima/chat-firebase#1]
i am getting error while registring /users.json" in this showing 

  com.firebase.client.FirebaseException: Invalid Firebase path: /users.json. Firebase paths must not contain '.', '#', '$', '[', or ']'
        at com.firebase.client.utilities.Validation.validatePathString(Validation.java:36)
        at com.firebase.client.utilities.Validation.validateRootPathString(Validation.java:47)
        at com.firebase.client.utilities.Utilities.parseUrl(Utilities.java:43)
        at com.firebase.client.Firebase.<init>(Firebase.java:155)
        at ir.mirrajabi.firebasecoolchat.Register$2$1.onResponse(Register.java:81)
        at ir.mirrajabi.firebasecoolchat.Register$2$1.onResponse(Register.java:78)

**Comment by tashish24** [comment]
wheres recyclerview.java file buddy. ain't getting that file
